
#define CONFIG_USE_UDPFRONT
#define CONFIG_USE_LRMODFRONT
#define CONFIG_USE_EXTNS
#define CONFIG_SUPPORT_EMBEDNS
#define CONFIG_SUPPORT_WEB
#define CONFIG_SUPPORT_HMI
#define CONFIG_FIX_CPPSTD

TARGET = nanobone
PROD_MACROS = CONFIG_USE_LRMODFRONT CONFIG_USE_EXTNS CONFIG_SUPPORT_WEB CONFIG_SUPPORT_HMI CONFIG_FIX_CPPSTD CONFIG_SUPPORT_SIGN
PROD_LIBS = curl ssl crypto

include make/main.mak
