
#define CONFIG_USE_UDPFRONT
#define CONFIG_USE_LRMODFRONT
#define CONFIG_USE_EXTNS
#define CONFIG_SUPPORT_EMBEDNS
#define CONFIG_SUPPORT_WEB

TARGET = sdkbone
TOOLCHAIN = native
PROD_MACROS = CONFIG_USE_UDPFRONT CONFIG_USE_EXTNS CONFIG_FORCE_RADIO0TX CONFIG_SUPPORT_HWAUTH CONFIG_SUPPORT_REST
PROD_LIBS = curl ssl crypto

include make/main.mak
